### PR TITLE
Add TLSv1.2 support

### PR DESCRIPTION
**Pull request by navewindre**
replaces the TlsClient implementation with code taken from https://github.com/melonedo/zig-tls12.
this seems to work fine with TLSv1.2 compatible servers. it's pretty much a drop-in replacement.

also fixes compilation error due to invalid fields in timeval struct.

edit: reading through the commit history it seems that the .tv_sec and .tv_nsec fields were changed in some zig version. i don't know if the intended target is the latest dev branch of zig or stable 0.13.0, so it may be that those changes are unnecessary. apologies if they are.

### CODE REVIEW

**Comment by karlseguin** [comment]
I think security-related code requires a higher standard: it needs to be battle-tested and independently audited.  For that reason, I'm not going to accept this PR.

I do agree the TLS situation in Zig is an issue, it's unclear whether we'll see a "battle-tested and independently audited" TLS implement in stdlib. 

Over the next couple weeks, I'll look at possible sustainable options. Most likely, I'll end up using BearSSL.

Also the `_sec` suffix was removed ~1.5 months ago or so.

**Comment by karlseguin** [comment]
I have an experimental branch in pg.zig which uses openssl. Once I've completed that work, I'll probably implement something similar here.
